<?php
function shift_cipher_menu() {
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['shift_cipher_results_page'] = array(
        'title' => 'Results',
        'page callback' => 'shift_cipher_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shift_cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Please enter the numeric value by which you would like to shift your letters.'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['direction'] = array(
        '#title' => 'Direction to Shift',
        '#type' => 'textfield',
        '#description' => t('Please specify if you would like the letters to shift right or left.'),
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );
    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Please enter the phrase to be encrypted.'),
        '#element_validate' => array('element_validate_phrase'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt!',
    );
    return $form;
}

function element_validate_direction($element) {
    $user_direction_input = strtolower($element['#value']);
    if (!($user_direction_input == 'right' || $user_direction_input == 'left')) {
        form_error($element, t("Please enter either 'right' or 'left'"));
    }
}

function element_validate_phrase($element) {
    $user_phrase = strtolower($element['#value']);
    $split_phrase = str_split($user_phrase);
    $accepted_chars = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ', '.', ',', '?', '!', ':', ';');
    foreach($split_phrase as $character) {
        if(!in_array($character, $accepted_chars)) {
            form_error($element, t('No special charcters allowed. Please enter only letters, spaces and punctuation(,.?!:;)'));
        }
    }
}
