<?php
function shift_cipher_menu() {
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['shift_cipher_results_page'] = array(
        'title' => 'Results',
        'page callback' => 'shift_cipher_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shift_cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Please enter the numeric value by which you would like to shift your letters.'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['direction'] = array(
        '#title' => 'Direction to Shift',
        '#type' => 'textfield',
        '#description' => t('Please specify if you would like the letters to shift right or left.'),
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );
    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Please enter the phrase to be encrypted.'),
        '#element_validate' => array('element_validate_phrase'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt!',
    );
    return $form;
}

function element_validate_direction($element) {
    $user_direction_input = strtolower($element['#value']);
    if (!($user_direction_input == 'right' || $user_direction_input == 'left')) {
        form_error($element, t("Please enter either 'right' or 'left'"));
    }
}

function element_validate_phrase($element) {
    $user_phrase = strtolower($element['#value']);
    $split_phrase = str_split($user_phrase);
    $accepted_chars = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ', '.', ',', '?', '!', ':', ';');
    foreach($split_phrase as $character) {
        if(!in_array($character, $accepted_chars)) {
            form_error($element, t('No special charcters allowed. Please enter only letters, spaces and punctuation(,.?!:;)'));
        }
    }
}

function shift_cipher_form_submit($form, &$form_state) {
    //grab values from form
    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['direction'];
    $phrase = $form_state['values']['phrase'];
    //make the phrase lower case and split it into an array
    $lower_phrase = strtolower($phrase);
    $split_phrase = str_split($lower_phrase);
    //create an array with the alphabet in order. keys are inherrently numeric.
    $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');

    // determine whether or not shift value will be added or subtracted based on direction
    if($direction == 'left') {
        $shift_direction = -1;
    } else {
        $shift_direction = 1;
    }
    //somewhere in here, use array_search(). It searches an array for a value and returns the key.
    $result = "";
    //loop through the phrase
    foreach($split_phrase as $letter) {
        //find the characters in the phrase which are letters
        if(in_array($letter, $alphabet)) {
            //find each letter's numeric key for mathing
            $key = array_search($letter, $alphabet);
            //math equation to encrypt each letter
            $encrypted_letter = $key + ($shift_direction * $shift_value);
            //turn the numeric key back into it's corresponding letter value
            $result .= $alphabet[$encrypted_letter];
        //if it is punctuation and not a letter, add it to the result output
        } else {
            $result .= $letter;
        }
        $form_state['redirect'] = 'shift_cipher_results_page';
    }
    $_SESSION['results'] = $result;
}

function shift_cipher_results() {
    $result = $_SESSION['results'];
    return "Your encrypted phrase is: $result";
}
